### ISSUE TITLE
实战中cookie默认设置为rememberMe会触发一些网站的waf导致发包不成功，从而漏掉很多重要指纹

### ISSUE THREAD

**Issue by kasjhkjaSD** [kN6jq/fingerScan#1]
![image](https://github.com/kN6jq/fingerScan/assets/67731867/8e22c3f9-baa3-44ff-a392-63301800cb10)

**Comment by kN6jq** [comment]
了解  抽空改一下

**Comment by kN6jq** [comment]
该问题已修复
